version: "3.9"

services:
  api:
    build: .
    image: cellannot-gpt-api:latest
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - CELLANNOT_DATA_DIR=/data
    volumes:
      - ./data/processed:/data
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
