name: CI

on:
  push:
    branches: ["main", "develop"]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction --with dev

      - name: Ruff lint
        run: poetry run ruff check backend frontend evaluation scripts config tests

      - name: Black format check
        run: poetry run black --check backend frontend evaluation scripts config tests

      - name: Mypy type check
        run: poetry run mypy backend

      - name: Run unit tests
        run: poetry run pytest

      - name: Build Docker image
        run: docker build -t cellannot-gpt-ci .
