name: pkgdown (gptcellannotator)

on:
  push:
    branches: [main]
    paths:
      - 'clients/r/gptcellannotator/**'
      - '.github/workflows/pkgdown.yml'
  release:
    types: [published]
  workflow_dispatch: {}

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install package dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: clients/r/gptcellannotator
          extra-packages: |
            any::pkgdown
            local::.
          needs: website

      - name: Build pkgdown site
        working-directory: clients/r/gptcellannotator
        run: Rscript -e "pkgdown::build_site(preview = FALSE)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: clients/r/gptcellannotator/docs
          keep_files: false
